#!/bin/bash

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-2 -d 9

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config presel_feedback false
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true

bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc rule -a feh state=floating
bspc rule -a yandex-music state=floating

xrdb merge ~/.Xresources

~/.screenlayout/w.sh &
~/.config/polybar/launch.sh &

/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-gtk &

sxhkd &
setxkbmap -layout us,ru -variant , -option grp:alt_shift_toggle &
feh --bg-fill ~/Pictures/Wallpapers/9.png &
picom --config ~/.config/bspwm/picom/picom.conf &
